#!/bin/bash

## LOCAL BASH SETTINGS ##
 export profileDir="$HOME/.jejackso_settings"

#Grab variables
 #export pVAR=$profileDir/var
  #for f in $pVAR/*;do source $f; done
 export pBIN=$profileDir/bin
 export pLIB=$profileDir/lib
 #active should be a symlink to the local machine
 export lBIN=$profileDir/bin/ihc
 export pENV=$profileDir/env
 
#add Aliases
 export pALS=$profileDir/aliases
 for f in $pALS/*;do if [ ! -d $f ]; then source $f;fi;done

#set up color command prompt
 source $pENV/color_command_prompt
 
 #set PATH
 PATH=$PATH:$lBIN:$pBIN/global:$pBIN/networking:$pBIN/password

#Run custom login scripts
 if [ -d "$pENV/active/startup_scripts" ]; then
   for f in $pENV/startup_scripts/*;do if [ ! -d $f ]; then if [ "$f" == "$(hostname)" ]; then `$f` ;fi;fi;done
 fi
